version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: bantaioskm
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: oskmdb
      POSTGRES_HOST: db
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
